name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🛠 Breaking Changes"
    labels:
      - "major"
      - "breaking change"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
      - "minor"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: Other Changes
    labels:
      - "*"
exclude-labels:
  - "tagpr"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Container Image

  ```sh
  docker pull ghcr.io/lirlia/prel:${RESOLVED_VERSION}
  ```
