CREATE TABLE users (
    id TEXT PRIMARY KEY NOT NULL,
    google_id TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    is_available BOOLEAN NOT NULL,
    role TEXT NOT NULL,
    session_id TEXT NOT NULL,
    session_expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_signin_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE requests (
    id TEXT PRIMARY KEY NOT NULL,
    requester_user_id TEXT NOT NULL REFERENCES users(id),
    judger_user_id TEXT REFERENCES users(id),
    status TEXT NOT NULL,
    project_id TEXT NOT NULL,
    iam_roles TEXT NOT NULL,
    period INTEGER NOT NULL,
    reason TEXT NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    judged_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invitations (
    id TEXT PRIMARY KEY NOT NULL,
    inviter_user_id TEXT NOT NULL REFERENCES users(id),
    invitee_mail TEXT NOT NULL UNIQUE,
    invitee_role TEXT NOT NULL,
    invited_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE iam_role_filtering_rules (
    id TEXT PRIMARY KEY NOT NULL,
    pattern TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE setting (
    id TEXT PRIMARY KEY NOT NULL,
    notification_message_for_request TEXT,
    notification_message_for_judge TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
