// Code generated by ogen, DO NOT EDIT.
package api

type APIIamRoleFilteringRulesGetRes interface {
	aPIIamRoleFilteringRulesGetRes()
}

type APIIamRoleFilteringRulesPostRes interface {
	aPIIamRoleFilteringRulesPostRes()
}

type APIIamRoleFilteringRulesRuleIDDeleteRes interface {
	aPIIamRoleFilteringRulesRuleIDDeleteRes()
}

type APIIamRolesGetRes interface {
	aPIIamRolesGetRes()
}

type APIInvitationsPostRes interface {
	aPIInvitationsPostRes()
}

type APIRequestsGetRes interface {
	aPIRequestsGetRes()
}

type APIRequestsPostRes interface {
	aPIRequestsPostRes()
}

type APIRequestsRequestIDDeleteRes interface {
	aPIRequestsRequestIDDeleteRes()
}

type APIRequestsRequestIDPatchRes interface {
	aPIRequestsRequestIDPatchRes()
}

type APIUsersGetRes interface {
	aPIUsersGetRes()
}

type APIUsersUserIDPatchRes interface {
	aPIUsersUserIDPatchRes()
}

type AdminIamRoleFilteringGetRes interface {
	adminIamRoleFilteringGetRes()
}

type AdminRequestGetRes interface {
	adminRequestGetRes()
}

type AdminUserGetRes interface {
	adminUserGetRes()
}

type AuthGoogleCallbackGetRes interface {
	authGoogleCallbackGetRes()
}

type GetRes interface {
	getRes()
}

type HealthGetRes interface {
	healthGetRes()
}

type RequestFormGetRes interface {
	requestFormGetRes()
}

type RequestGetRes interface {
	requestGetRes()
}

type RequestRequestIDGetRes interface {
	requestRequestIDGetRes()
}

type SigninPostRes interface {
	signinPostRes()
}

type SignoutPostRes interface {
	signoutPostRes()
}
