// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIIamRoleFilteringRulesGet implements GET /api/iam-role-filtering-rules operation.
//
// Return iam role filtering rules.
//
// GET /api/iam-role-filtering-rules
func (UnimplementedHandler) APIIamRoleFilteringRulesGet(ctx context.Context) (r APIIamRoleFilteringRulesGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIIamRoleFilteringRulesPost implements POST /api/iam-role-filtering-rules operation.
//
// Post iam role filtering rule.
//
// POST /api/iam-role-filtering-rules
func (UnimplementedHandler) APIIamRoleFilteringRulesPost(ctx context.Context, req *APIIamRoleFilteringRulesPostReq) (r APIIamRoleFilteringRulesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIIamRoleFilteringRulesRuleIDDelete implements DELETE /api/iam-role-filtering-rules/{ruleID} operation.
//
// Delete rule.
//
// DELETE /api/iam-role-filtering-rules/{ruleID}
func (UnimplementedHandler) APIIamRoleFilteringRulesRuleIDDelete(ctx context.Context, params APIIamRoleFilteringRulesRuleIDDeleteParams) (r APIIamRoleFilteringRulesRuleIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIIamRolesGet implements GET /api/iam-roles operation.
//
// Return iam roles in project id.
//
// GET /api/iam-roles
func (UnimplementedHandler) APIIamRolesGet(ctx context.Context, params APIIamRolesGetParams) (r APIIamRolesGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIInvitationsPost implements POST /api/invitations operation.
//
// Create user invitation.
//
// POST /api/invitations
func (UnimplementedHandler) APIInvitationsPost(ctx context.Context, req *APIInvitationsPostReq) (r APIInvitationsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIRequestsGet implements GET /api/requests operation.
//
// Return admin request with paging.
//
// GET /api/requests
func (UnimplementedHandler) APIRequestsGet(ctx context.Context, params APIRequestsGetParams) (r APIRequestsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIRequestsPost implements POST /api/requests operation.
//
// Post request.
//
// POST /api/requests
func (UnimplementedHandler) APIRequestsPost(ctx context.Context, req *APIRequestsPostReq) (r APIRequestsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIRequestsRequestIDDelete implements DELETE /api/requests/{requestID} operation.
//
// Delete request.
//
// DELETE /api/requests/{requestID}
func (UnimplementedHandler) APIRequestsRequestIDDelete(ctx context.Context, params APIRequestsRequestIDDeleteParams) (r APIRequestsRequestIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIRequestsRequestIDPatch implements PATCH /api/requests/{requestID} operation.
//
// Update request.
//
// PATCH /api/requests/{requestID}
func (UnimplementedHandler) APIRequestsRequestIDPatch(ctx context.Context, req *APIRequestsRequestIDPatchReq, params APIRequestsRequestIDPatchParams) (r APIRequestsRequestIDPatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIUsersGet implements GET /api/users operation.
//
// Return admin user with paging.
//
// GET /api/users
func (UnimplementedHandler) APIUsersGet(ctx context.Context, params APIUsersGetParams) (r APIUsersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIUsersUserIDPatch implements PATCH /api/users/{userID} operation.
//
// Update user.
//
// PATCH /api/users/{userID}
func (UnimplementedHandler) APIUsersUserIDPatch(ctx context.Context, req *APIUsersUserIDPatchReq, params APIUsersUserIDPatchParams) (r APIUsersUserIDPatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminIamRoleFilteringGet implements GET /admin/iam-role-filtering operation.
//
// Return iam role filtering page.
//
// GET /admin/iam-role-filtering
func (UnimplementedHandler) AdminIamRoleFilteringGet(ctx context.Context) (r AdminIamRoleFilteringGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminRequestGet implements GET /admin/request operation.
//
// Return admin request page.
//
// GET /admin/request
func (UnimplementedHandler) AdminRequestGet(ctx context.Context) (r AdminRequestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUserGet implements GET /admin/user operation.
//
// Return admin user page.
//
// GET /admin/user
func (UnimplementedHandler) AdminUserGet(ctx context.Context) (r AdminUserGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthGoogleCallbackGet implements GET /auth/google/callback operation.
//
// Google callback endpoint.
//
// GET /auth/google/callback
func (UnimplementedHandler) AuthGoogleCallbackGet(ctx context.Context, params AuthGoogleCallbackGetParams) (r AuthGoogleCallbackGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Get implements GET / operation.
//
// Display top page.
//
// GET /
func (UnimplementedHandler) Get(ctx context.Context, params GetParams) (r GetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthGet implements GET /health operation.
//
// Healthcheck.
//
// GET /health
func (UnimplementedHandler) HealthGet(ctx context.Context) (r HealthGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestFormGet implements GET /request-form operation.
//
// Get request form.
//
// GET /request-form
func (UnimplementedHandler) RequestFormGet(ctx context.Context) (r RequestFormGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestGet implements GET /request operation.
//
// Return request list page.
//
// GET /request
func (UnimplementedHandler) RequestGet(ctx context.Context) (r RequestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestRequestIDGet implements GET /request/{requestID} operation.
//
// Get request page.
//
// GET /request/{requestID}
func (UnimplementedHandler) RequestRequestIDGet(ctx context.Context, params RequestRequestIDGetParams) (r RequestRequestIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SigninPost implements POST /signin operation.
//
// Sign in.
//
// POST /signin
func (UnimplementedHandler) SigninPost(ctx context.Context, params SigninPostParams) (r SigninPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SignoutPost implements POST /signout operation.
//
// Sign out.
//
// POST /signout
func (UnimplementedHandler) SignoutPost(ctx context.Context) (r SignoutPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
